stages:
  download:
    cmd: python download.py
    params:
      - data
    deps:
      - download.py
    outs:
      - data/train_dataset.pkl
      - data/val_dataset.pkl
      - data/test_dataset.pkl

  train:
    cmd: python train.py
    params:
      - training.epochs
      - training.batch_size
      - training.optimizer
      - model
      - logging
      - artifacts
    deps:
      - train.py
      - data/train_dataset.pkl
      - data/val_dataset.pkl
    outs:
      - artifacts/best_model.pth
      - logs/training.log

  evaluate:
    cmd: python evaluate.py
    params:
      - evaluation.metrics
      - artifacts.output_dir
    deps:
      - artifacts/best_model.pth
      - data/test_dataset.pkl
      - evaluate.py
    metrics:
      - artifacts/metrics.json
